baseURL = "http://luca-spopo.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Luca's Trove"
enableRobotsTXT = true
enableEmoji = true
theme = "even"
publishDir = "docs"

logo-font-size = 3

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 3                                              # （可选）首页显示的文章条目数量，默认为10
disqusShortname = "anirudh-katoch-me"      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓

[author]                  # require                       # 必需
  name = "Anirudh Katoch"

[sitemap]                 # require                       # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

#Configure your menu

[[menu.main]]
  name = "About me"
  weight = 10
  identifier = "aboutme"
  url = "/about/"
[[menu.main]]
  name = "Portfolio"
  weight = 20
  identifier = "portfolio"
  url = "/portfolio/"
[[menu.main]]
  name = "Projects"
  weight = 30
  identifier = "projects"
  url = "/project/"
[[menu.main]]
  name = "Blogs"
  weight = 40
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "Tutorials"
  weight = 50
  identifier = "tutorial"
  url = "/tutorial/"

[params]
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  email = "katoch.anirudh@gmail.com"
  since = "2017"            # Site creation time          # 站点建立时间

  # site info (option)                                    # 站点信息（可选）
  logoTitle = "Luca's Trove"        # default: the title value    # 默认值: 上面设置的title值
  logoCount = 7
  keywords = ["Katoch", "Anirudh", "Job", "Software", "Engineer"]
  description = "Anirudh Katoch's personal website."
  globalColor1 = "#c05b4d"

  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目
  archive-paginate = 10

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "January 2, 2006"

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta = false

  # 一些全局开关，你可以在每一篇内容的 front matter 中单独关闭某些选项
  # Some global options, you can close something in front matter.
  toc = true                                                                            # 是否开启目录
  fancybox = true           # see https://github.com/fancyapps/fancybox                 # 是否启用fancybox（图片可点击）
  bootcdn = false           # In china. @Deprecated: use [params.publicCDN]             # 是否使用bootcdn(@Deprecated: 请使用[params.publicCDN])
  mathjax = true            # see https://www.mathjax.org/                              # 是否使用mathjax（数学公式）
  linkToMarkDown = false    # if you config contentCopyright and hugo output .md files. # 是否在链接到markdown原始文件（如果你配置了下面的许可协议并允许hugo生成markdown文件）

  contentCopyright = ''

  changyanAppid = ""        # Changyan app id             # 畅言
  changyanAppkey = ""       # Changyan app key
  baidu_push = false        # baidu push                  # 百度
  baidu_analytics = ""      # Baidu Analytics
  baidu_verification = ""   # Baidu Verification
  google_verification = ""  # Google_Verification         # 谷歌

  [params.publicCDN]        # load these files from public cdn                          # 启用公共CDN，需自行定义
    enable = false
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    fancyboxJs = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
    fancyboxCss = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'

  [params.reward]                                         # 文章打赏
    enable = false
    #wechat = "/path/to/your/wechat-qr-code.png"           # 微信二维码
    #alipay = "/path/to/your/alipay-qr-code.png"           # 支付宝二维码

  [params.social]                                         # 社交链接
    #a-email = "sa"
    #b-stack-overflow = "http://localhost:1313"
    #c-twitter = "http://localhost:1313"
    #d-facebook = "http://localhost:1313"
    e-linkedin = "https://www.linkedin.com/in/anirudh-katoch-b24685127/"
    #f-google = ""
    g-github = "http://www.github.com/luca-spopo"
    #h-weibo = "http://localhost:1313"
    #i-zhihu = "http://localhost:1313"
    #j-douban = "http://localhost:1313"
    #k-pocket = "http://localhost:1313"
    #l-tumblr = "http://localhost:1313"
    #m-instagram = "http://localhost:1313"

# 将下面这段配置取消注释可以使 hugo 生成 .md 文件
# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffix = "md"
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
